services:
 postgres:
  image: postgres:17-alpine
  container_name: startime-postgres
  restart: always
  environment:
   POSTGRES_DB: startime
   POSTGRES_USER: startime
   POSTGRES_PASSWORD: startime
  ports:
   - "6543:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
  healthcheck:
   test: ["CMD-SHELL", "pg_isready -U startime -d startime"]
   interval: 5s
   timeout: 5s
   retries: 10

 redis:
  image: redis:7-alpine
  container_name: startime-redis
  restart: always
  ports:
   - "6379:6379"
  volumes:
   - redis_data:/data
  networks:
   - default
  command: redis-server --requirepass password
  healthcheck:
   test: ["CMD", "redis-cli", "ping"]
   interval: 5s
   timeout: 5s
   retries: 10

 redis-insight:
  image: redis/redisinsight:latest
  container_name: startime_insight
  restart: always
  ports:
   - "5540:5540"
  volumes:
   - redis_insight_data:/data
  networks:
   - default

volumes:
 postgres_data:
 redis_data:
 redis_insight_data:

networks:
 default:
  driver: bridge
