export const languageLabel = {
	abap: "ABAP",
	actionscript: "ActionScript",
	ada: "Ada",
	apex: "Apex",
	applescript: "AppleScript",
	arduino: "Arduino",
	assembly: "Assembly",
	astro: "Astro",
	awk: "Awk",
	bash: "Bash",
	bat: "Batchfile",
	bicep: "Bicep",
	blade: "Blade",
	c: "C",
	clojure: "Clojure",
	cmake: "CMake",
	cobol: "COBOL",
	coffeescript: "CoffeeScript",
	cpp: "C++",
	csharp: "C#",
	css: "CSS",
	cucumber: "Gherkin",
	cuda: "CUDA",
	d: "D",
	dart: "Dart",
	delphi: "Delphi",
	dockerfile: "Dockerfile",
	elixir: "Elixir",
	elm: "Elm",
	erlang: "Erlang",
	fsharp: "F#",
	fortran: "Fortran",
	"git-config": "Git Config",
	go: "Go",
	graphql: "GraphQL",
	groovy: "Groovy",
	handlebars: "Handlebars",
	haskell: "Haskell",
	hcl: "HCL",
	html: "HTML",
	ini: "INI",
	java: "Java",
	javascript: "JavaScript",
	javascriptreact: "JavaScript React",
	jinja: "Jinja",
	json: "JSON",
	julia: "Julia",
	kotlin: "Kotlin",
	latex: "LaTeX",
	less: "Less",
	lisp: "Lisp",
	lua: "Lua",
	makefile: "Makefile",
	markdown: "Markdown",
	matlab: "MATLAB",
	nim: "Nim",
	nix: "Nix",
	objectivec: "Objective-C",
	ocaml: "OCaml",
	pascal: "Pascal",
	perl: "Perl",
	php: "PHP",
	plsql: "PL/SQL",
	postcss: "PostCSS",
	powershell: "PowerShell",
	prisma: "Prisma",
	prolog: "Prolog",
	properties: "Properties",
	pug: "Pug",
	puppet: "Puppet",
	python: "Python",
	r: "R",
	razor: "Razor",
	ruby: "Ruby",
	rust: "Rust",
	sas: "SAS",
	sass: "Sass",
	scala: "Scala",
	scss: "SCSS",
	shaderlab: "ShaderLab",
	shellscript: "Shell Script",
	solidity: "Solidity",
	sql: "SQL",
	svelte: "Svelte",
	swift: "Swift",
	toml: "TOML",
	tslink: "TSLink",
	typescript: "TypeScript",
	typescriptreact: "TypeScript React",
	vb: "Visual Basic",
	vba: "VBA",
	vbscript: "VBScript",
	vue: "Vue",
	xml: "XML",
	yaml: "YAML",
	zig: "Zig",
};

export const getLanguageLabel = (language: string) => {
	return languageLabel[language as keyof typeof languageLabel] ?? language;
};
